language: java

addons:
  sonarcloud:
    organization: "ahmedriahi-github"
    token:
      secure: 5a5a0c07cbcaef323f6d9de346b4bdb88d3eeb9b
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -P TRAVIS_BUILD
  - sonar-scanner